import type { Metadata } from "next";
import {  Montserrat } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import Footer from "./component/footer/footer";
import Navbar from "./component/navbar/navbar";
import Chat from "./component/chat/chat";
import Script from "next/script";

// load your Monik font
const monik = localFont({
  src: [
    {
      path: './fonts/Monik.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Monik.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-monik',
})

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Qilume",
  description: "Generated by create next app",
};
const jsonLdData = {
  "@context": "https://schema.org",
  "@type": ["HealthAndBeautyBusiness", "LocalBusiness"],
  "@id": "https://www.qilumeaesthetics.com/",
  "name": "Qilumé Aesthetics Clinic",
  "description": "QiLumé Aesthetics is a premium aesthetic and wellness clinic dedicated to helping you look and feel your best.",
  "disambiguatingDescription": "We specialize in advanced skincare, laser hair reduction, slimming treatments, and holistic wellness solutions tailored for both men and women.",
  "mainEntityOfPage": "https://www.qilumeaesthetics.com/",
  "url": "https://www.qilumeaesthetics.com/",
  "telephone": "+919667929992",
  "priceRange": "$$$",
  "currenciesAccepted": "INR",
  "paymentAccepted": ["cash", "check", "credit card"],
  "address": {
      "@type": "PostalAddress",
      "addressLocality": "Gurugram",
      "addressRegion": "Haryana",
      "addressCountry": "IN",
      "streetAddress": "P, Ground Floor, Plot No-2027, Sector 45, Gurugram, Haryana 122003",
      "postalCode": "122003"
  },
  "sameAs": [
    "https://www.instagram.com/qilume.co/",
    "https://www.linkedin.com/company/qilum%C3%A9-aesthetics/"
  ],
  "geo": {
      "@type": "GeoCoordinates",
      "latitude": "28.450113761880118",
      "longitude": "77.06926912698462"
  },
  "slogan": "Skin care clinic in Gurgaon",
  "hasMap": "https://maps.app.goo.gl/TvswcPeFdK6c945m6",
  "openingHoursSpecification": {
      "@type": "OpeningHoursSpecification",
       "dayOfWeek": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
      "opens": "10:00",
      "closes": "20:00",
  },
  "knowsLanguage": ["en-IN"],
  "knowsAbout": [
    "Aesthetic treatments and beauty services",
    "Botox and anti-aging treatments",
    "Dermal fillers and facial enhancement services",
    "Thread lift and skin tightening treatments",
    "HIFU skin lifting treatments",
    "Laser skin treatments and laser hair removal services",
    "Cryo T-Shock body contouring services",
    "Laser hair reduction treatments",
    "Dermaplaning and advanced facial services",
    "MediFacial and professional skincare treatments",
    "Salon hair services including cutting, coloring, and styling",
    "Beauty services including threading, waxing, manicure, and pedicure",
    "Ayurvedic wellness and therapeutic treatments"
  ],
  "logo": "https://www.qilumeaesthetics.com/logo.png",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/logo.png" />
        <link rel="shortcut icon" href="/logo.png" />
        <title>Qilumé Aesthetics | Advanced Aesthetic Treatments in Gurgaon</title>
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-76EMQBESRD"
        />  
        <Script id="google-analytics">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-76EMQBESRD');
          `}
        </Script>
        {/* Facebook Pixel */}
        <Script id="facebook-pixel" strategy="afterInteractive">
          {`
          !function(f,b,e,v,n,t,s)
          {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
          n.callMethod.apply(n,arguments):n.queue.push(arguments)};
          if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
          n.queue=[];t=b.createElement(e);t.async=!0;
          t.src=v;s=b.getElementsByTagName(e)[0];
          s.parentNode.insertBefore(t,s)}(window, document,'script',
          'https://connect.facebook.net/en_US/fbevents.js');
          fbq('init', '1498064454783636');
          fbq('track', 'PageView');
          `}
        </Script>
        <noscript>
          <img
            height="1"
            width="1"
            style={{ display: "none" }}
            src="https://www.facebook.com/tr?id=1498064454783636&ev=PageView&noscript=1"
          />
        </noscript>
        {/* Schema */}
        <Script
            id="json-ld-schema"
            strategy="afterInteractive" // or "beforeInteractive" if absolutely critical for initial render
            type="application/ld+json"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLdData) }}
          />
      </head>
      <body
        className={`${montserrat.variable} ${monik.variable}  antialiased`}
      >
        <Navbar/>
        <main>
          {children}
        </main>
        <Footer/>
        <Chat/>
      </body>
    </html>
  );
}
