import type { Metadata } from "next";
import {  Montserrat } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import Footer from "./component/footer/footer";
import Navbar from "./component/navbar/navbar";

// load your Monik font
const monik = localFont({
  src: [
    {
      path: './fonts/Monik.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Monik.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-monik',
})

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Qilume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${monik.variable}  antialiased`}
      >
        <Navbar/>
        <main>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
